version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: eb129/docker-kubectl
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build amd64 Docker Image
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --tag $IMAGE_NAME:$IMAGE_TAG .
  publish:
    environment:
      IMAGE_NAME: eb129/docker-kubectl
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish amd64 Docker Image to Docker Hub
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --tag $IMAGE_NAME:$IMAGE_TAG .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - publish:
          context: docker
          filters:
            branches:
              only: main
